// Landing page components barrel export
export { Section } from "./section"
export { GridBackground } from "./grid-background"
export { StatusBadge, type BadgeStatus } from "./status-badge"
export { DitherPattern } from "./dither-pattern"
export { Navbar } from "./navbar"
export { Hero } from "./hero"
export { BentoGrid } from "./bento-grid"
export { IntegrationMesh } from "./integration-mesh"
export { SocialProof } from "./social-proof"
export { Analytics } from "./analytics"
export { Testimonials } from "./testimonials"
export { Pricing } from "./pricing"
export { Footer } from "./footer"
